### ISSUE TITLE
Index error

### ISSUE THREAD

**Issue by borbysh** [haydengunraj/COVIDNet-CT#7]
Hi,
I'm trying to run training from a pretrained model. That's what I do and see:

d:\BORISENKO\Byshkin\CoolMomentum\CovidNet>python run_covidnet_ct.py train
2020-10-08 12:06:42.819427: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic libra
ry 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-10-08 12:06:42.827428: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do n
ot have a GPU set up on your machine.
2020-10-08 12:06:45.744594: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic libra
ry 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-10-08 12:06:45.750595: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (
303)
2020-10-08 12:06:45.757595: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic inform
ation for host: Aborisenko
2020-10-08 12:06:45.763596: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Aborisenko
Loading meta graph from models/COVIDNet-CT-A\model.meta
Loading weights from models/COVIDNet-CT-A\model
Saving baseline checkpoint
Starting baseline validation
        confusion matrix:
        [[9095   12    0]
         [  35 7327   38]
         [   0  343 4186]]
        COVID-19 PPV: 0.9910037878787878
        COVID-19 sensitivity: 0.9242658423493045
        Normal PPV: 0.9961664841182913
        Normal sensitivity: 0.9986823322718787
        Pneumonia PPV: 0.9537880760218693
        Pneumonia sensitivity: 0.9901351351351352
        accuracy: 0.9796539266020156
Training with batch_size 8 for 154460 steps
2020-10-08 12:58:43.165496: W tensorflow/core/framework/op_kernel.cc:1639] Unknown: IndexError: boolean index did not ma
tch indexed array along dimension 2; dimension is 1 but corresponding boolean dimension is 512
Traceback (most recent call last):

  File "C:\Python\WPy64-3771\python-3.7.7.amd64\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 235, i
n __call__
    ret = func(*args)

  File "d:\BORISENKO\Byshkin\CoolMomentum\CovidNet\data_utils.py", line 95, in exterior_exclusion
    bg_mean = np.mean(image[bg_dark])

IndexError: boolean index did not match indexed array along dimension 2; dimension is 1 but corresponding boolean dimens
ion is 512

Could you please advise something?

**Comment by borbysh** [comment]
There is no such bug in the latest version, thanks for fixing it
